apiVersion: 
kind: 
metadata:
  name: {{.value.service.name}} 
spec:
  type: {{.value.service.type}}
  selector:
    app: {{.value.service.label}}
  ports:
    - port: {{.value.service.port}}
      targetPort: {{.value.service.port}}
      nodePort:  {{.value.service.nodeport}}
